package classes;
// Generated Mar 31, 2017 10:18:18 PM by Hibernate Tools 4.3.1



/**
 * TblQuina generated by hbm2java
 */
public class TblQuina  implements java.io.Serializable {


     private int concurso;
     private Integer primeiraDez;
     private Integer segundaDez;
     private Integer terceiraDez;
     private Integer quartaDez;
     private Integer quintaDez;
     private Integer ganhadoresQuina;
     private Double rateioQuina;
     private Integer ganhadoresQuadra;
     private Double rateioQuadra;

    public TblQuina() {
    }

	
    public TblQuina(int concurso) {
        this.concurso = concurso;
    }
    public TblQuina(int concurso, Integer primeiraDez, Integer segundaDez, Integer terceiraDez, Integer quartaDez, Integer quintaDez, Integer ganhadoresQuina, Double rateioQuina, Integer ganhadoresQuadra, Double rateioQuadra) {
       this.concurso = concurso;
       this.primeiraDez = primeiraDez;
       this.segundaDez = segundaDez;
       this.terceiraDez = terceiraDez;
       this.quartaDez = quartaDez;
       this.quintaDez = quintaDez;
       this.ganhadoresQuina = ganhadoresQuina;
       this.rateioQuina = rateioQuina;
       this.ganhadoresQuadra = ganhadoresQuadra;
       this.rateioQuadra = rateioQuadra;
    }
   
    public int getConcurso() {
        return this.concurso;
    }
    
    public void setConcurso(int concurso) {
        this.concurso = concurso;
    }
    public Integer getPrimeiraDez() {
        return this.primeiraDez;
    }
    
    public void setPrimeiraDez(Integer primeiraDez) {
        this.primeiraDez = primeiraDez;
    }
    public Integer getSegundaDez() {
        return this.segundaDez;
    }
    
    public void setSegundaDez(Integer segundaDez) {
        this.segundaDez = segundaDez;
    }
    public Integer getTerceiraDez() {
        return this.terceiraDez;
    }
    
    public void setTerceiraDez(Integer terceiraDez) {
        this.terceiraDez = terceiraDez;
    }
    public Integer getQuartaDez() {
        return this.quartaDez;
    }
    
    public void setQuartaDez(Integer quartaDez) {
        this.quartaDez = quartaDez;
    }
    public Integer getQuintaDez() {
        return this.quintaDez;
    }
    
    public void setQuintaDez(Integer quintaDez) {
        this.quintaDez = quintaDez;
    }
    public Integer getGanhadoresQuina() {
        return this.ganhadoresQuina;
    }
    
    public void setGanhadoresQuina(Integer ganhadoresQuina) {
        this.ganhadoresQuina = ganhadoresQuina;
    }
    public Double getRateioQuina() {
        return this.rateioQuina;
    }
    
    public void setRateioQuina(Double rateioQuina) {
        this.rateioQuina = rateioQuina;
    }
    public Integer getGanhadoresQuadra() {
        return this.ganhadoresQuadra;
    }
    
    public void setGanhadoresQuadra(Integer ganhadoresQuadra) {
        this.ganhadoresQuadra = ganhadoresQuadra;
    }
    public Double getRateioQuadra() {
        return this.rateioQuadra;
    }
    
    public void setRateioQuadra(Double rateioQuadra) {
        this.rateioQuadra = rateioQuadra;
    }




}


